name: Upload docs
on: [push]
jobs:
  upload-docs:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Build docs
        run: poetry run make html
        working-directory: docs
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DOCS_DEPLOY_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: replace
      - name: Push code
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub actions"
          git init
          git add .
          git commit -m "Update from nextcore build"
          git remote add origin git@github.com:nextsnake/nextcore-docs.git
          git push origin ${{ github.ref_name }} --force
        working-directory: docs
